/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as GalleriesRouteImport } from './routes/galleries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GalleriesIndexRouteImport } from './routes/galleries.index'
import { Route as GalleriesGroupRouteImport } from './routes/galleries.$group'
import { Route as GalleriesGroupIndexRouteImport } from './routes/galleries.$group.index'
import { Route as GalleriesGroupSlugRouteImport } from './routes/galleries.$group.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleriesRoute = GalleriesRouteImport.update({
  id: '/galleries',
  path: '/galleries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleriesIndexRoute = GalleriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GalleriesRoute,
} as any)
const GalleriesGroupRoute = GalleriesGroupRouteImport.update({
  id: '/$group',
  path: '/$group',
  getParentRoute: () => GalleriesRoute,
} as any)
const GalleriesGroupIndexRoute = GalleriesGroupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GalleriesGroupRoute,
} as any)
const GalleriesGroupSlugRoute = GalleriesGroupSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GalleriesGroupRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/galleries': typeof GalleriesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/galleries/$group': typeof GalleriesGroupRouteWithChildren
  '/galleries/': typeof GalleriesIndexRoute
  '/galleries/$group/$slug': typeof GalleriesGroupSlugRoute
  '/galleries/$group/': typeof GalleriesGroupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/galleries': typeof GalleriesIndexRoute
  '/galleries/$group/$slug': typeof GalleriesGroupSlugRoute
  '/galleries/$group': typeof GalleriesGroupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/galleries': typeof GalleriesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/galleries/$group': typeof GalleriesGroupRouteWithChildren
  '/galleries/': typeof GalleriesIndexRoute
  '/galleries/$group/$slug': typeof GalleriesGroupSlugRoute
  '/galleries/$group/': typeof GalleriesGroupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/galleries'
    | '/sitemap.xml'
    | '/galleries/$group'
    | '/galleries/'
    | '/galleries/$group/$slug'
    | '/galleries/$group/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/sitemap.xml'
    | '/galleries'
    | '/galleries/$group/$slug'
    | '/galleries/$group'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/galleries'
    | '/sitemap.xml'
    | '/galleries/$group'
    | '/galleries/'
    | '/galleries/$group/$slug'
    | '/galleries/$group/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GalleriesRoute: typeof GalleriesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galleries': {
      id: '/galleries'
      path: '/galleries'
      fullPath: '/galleries'
      preLoaderRoute: typeof GalleriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galleries/': {
      id: '/galleries/'
      path: '/'
      fullPath: '/galleries/'
      preLoaderRoute: typeof GalleriesIndexRouteImport
      parentRoute: typeof GalleriesRoute
    }
    '/galleries/$group': {
      id: '/galleries/$group'
      path: '/$group'
      fullPath: '/galleries/$group'
      preLoaderRoute: typeof GalleriesGroupRouteImport
      parentRoute: typeof GalleriesRoute
    }
    '/galleries/$group/': {
      id: '/galleries/$group/'
      path: '/'
      fullPath: '/galleries/$group/'
      preLoaderRoute: typeof GalleriesGroupIndexRouteImport
      parentRoute: typeof GalleriesGroupRoute
    }
    '/galleries/$group/$slug': {
      id: '/galleries/$group/$slug'
      path: '/$slug'
      fullPath: '/galleries/$group/$slug'
      preLoaderRoute: typeof GalleriesGroupSlugRouteImport
      parentRoute: typeof GalleriesGroupRoute
    }
  }
}

interface GalleriesGroupRouteChildren {
  GalleriesGroupSlugRoute: typeof GalleriesGroupSlugRoute
  GalleriesGroupIndexRoute: typeof GalleriesGroupIndexRoute
}

const GalleriesGroupRouteChildren: GalleriesGroupRouteChildren = {
  GalleriesGroupSlugRoute: GalleriesGroupSlugRoute,
  GalleriesGroupIndexRoute: GalleriesGroupIndexRoute,
}

const GalleriesGroupRouteWithChildren = GalleriesGroupRoute._addFileChildren(
  GalleriesGroupRouteChildren,
)

interface GalleriesRouteChildren {
  GalleriesGroupRoute: typeof GalleriesGroupRouteWithChildren
  GalleriesIndexRoute: typeof GalleriesIndexRoute
}

const GalleriesRouteChildren: GalleriesRouteChildren = {
  GalleriesGroupRoute: GalleriesGroupRouteWithChildren,
  GalleriesIndexRoute: GalleriesIndexRoute,
}

const GalleriesRouteWithChildren = GalleriesRoute._addFileChildren(
  GalleriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GalleriesRoute: GalleriesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
