/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as GalleriesRouteImport } from './routes/galleries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GalleriesIndexRouteImport } from './routes/galleries.index'
import { Route as GalleriesSlugRouteImport } from './routes/galleries.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleriesRoute = GalleriesRouteImport.update({
  id: '/galleries',
  path: '/galleries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleriesIndexRoute = GalleriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GalleriesRoute,
} as any)
const GalleriesSlugRoute = GalleriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GalleriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/galleries': typeof GalleriesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/galleries/$slug': typeof GalleriesSlugRoute
  '/galleries/': typeof GalleriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/galleries/$slug': typeof GalleriesSlugRoute
  '/galleries': typeof GalleriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/galleries': typeof GalleriesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/galleries/$slug': typeof GalleriesSlugRoute
  '/galleries/': typeof GalleriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/galleries'
    | '/sitemap.xml'
    | '/galleries/$slug'
    | '/galleries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/sitemap.xml'
    | '/galleries/$slug'
    | '/galleries'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/galleries'
    | '/sitemap.xml'
    | '/galleries/$slug'
    | '/galleries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GalleriesRoute: typeof GalleriesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galleries': {
      id: '/galleries'
      path: '/galleries'
      fullPath: '/galleries'
      preLoaderRoute: typeof GalleriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galleries/': {
      id: '/galleries/'
      path: '/'
      fullPath: '/galleries/'
      preLoaderRoute: typeof GalleriesIndexRouteImport
      parentRoute: typeof GalleriesRoute
    }
    '/galleries/$slug': {
      id: '/galleries/$slug'
      path: '/$slug'
      fullPath: '/galleries/$slug'
      preLoaderRoute: typeof GalleriesSlugRouteImport
      parentRoute: typeof GalleriesRoute
    }
  }
}

interface GalleriesRouteChildren {
  GalleriesSlugRoute: typeof GalleriesSlugRoute
  GalleriesIndexRoute: typeof GalleriesIndexRoute
}

const GalleriesRouteChildren: GalleriesRouteChildren = {
  GalleriesSlugRoute: GalleriesSlugRoute,
  GalleriesIndexRoute: GalleriesIndexRoute,
}

const GalleriesRouteWithChildren = GalleriesRoute._addFileChildren(
  GalleriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GalleriesRoute: GalleriesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
